### ISSUE TITLE
Can it work in the Mac M1?

### ISSUE THREAD

**Issue by bcdavasconcelos** [yohasebe/ruby-spacy#1]
Just curious if anyone could get it to work in the mac M1. I tried recompiling python with the `--enable-shared` flag, by I keep getting the same error from PyCall.

```
Task Terminated with exit code 1
<internal:/username/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': Unable to find the required symbol in libpython: _Py_NoneStruct (PyCall::LibPythonFunctionNotFound)
    from <internal:/username/.rbenv/versions/3.1.0-dev/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    from /username/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/pycall-1.4.1/lib/pycall/init.rb:39:in `init'
    from /username/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/pycall-1.4.1/lib/pycall/init.rb:16:in `const_missing'
    from /username/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/pycall-1.4.1/lib/pycall.rb:74:in `import_module'
    from /username/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/pycall-1.4.1/lib/pycall/import.rb:18:in `pyimport'
    from /pathtoscript/untitled7.rb:20:in `<main>'
```

**Comment by yohasebe** [comment]
I have PyCall and ruby-spacy working fine on my M1 mac. If possible, would you please remove your current python environent altogether and reinstall it from scratch?

Notice that in order to compile python with `--enable-shared`  using pyenv, you may need to set the environemnt varialbe `CONFIGURE_OPTS` instead of just placing it as an option flag to `pyenv install` command. Like so:

`env CONFIGURE_OPTS="--enable-shared" pyenv install 3.9.5`

**Comment by bcdavasconcelos** [comment]
Thanks, @yohasebe! I managed to get it to work. The problem was the value of the PYTHON env variable. Once I pointed it to the right place (`export PYTHON="/Users/user/.pyenv/versions/3.9.6/bin/python3.9"`) it started working.
